version: '3.8'

services:
  homer:
    image: b4bz/homer
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./assets/:/www/assets
    environment:
      - PUID="${UID:-pi}"
      - PGID="${GID:-pi}"